    log_format http4xx-50
        '$time_iso8601 '
        '$msec '
        'rm="$request_method" '
        'r="$request" '
        'ru="$request_uri" '
        'q="$query_string" '
        'u="$uri" '
        'url="$scheme://$host$request_uri" '
        's="$status" '
        'ref="$http_referer" '
    ;
