    log_format http4xx-50
        '$time_iso8601 '
        '$msec '
        'rqmth="$request_method" '
        'rq="$request" '
        'rquri="$request_uri" '
        'q="$query_string" '
        'uri="$uri" '
        'url="$scheme://$host$request_uri" '
        'sts="$status" '
        'htref="$http_referer" '
    ;
