    log_format ip-30
        '$time_iso8601 '
        '$msec '
        'ip="$remote_addr" '
        'q="$query_string" '
        'uri="$uri" '
        'url="$scheme://$host$request_uri" '
        'sts="$status" '
    ;
