    log_format ips-70
        '$time_iso8601 '
        '$msec '
        'ips="$remote_addr_ipscrub" '
        'rqmth="$request_method" '
        'rq="$request" '
        'rquri="$request_uri" '
        'q="$query_string" '
        'uri="$uri" '
        'url="$scheme://$host$request_uri" '
        'sts="$status" '
        'rqlen="$request_length" '
        'rqtm="$request_time" '
        'upsts="$upstream_status" '
        'upctm="$upstream_connect_time" '
        'uprtm="$upstream_response_time" '
        'uprln="$upstream_response_length" '
        'uphtm="$upstream_header_time" '
        'upbyr="$upstream_bytes_received" '
        'upbys="$upstream_bytes_sent" '
        'upcac="$upstream_cache_status" '
        'srvad="$server_addr" '
		'srvpt="$server_port" '
        'srvpr="$server_protocol" '
        'h2="$http2" '
        'h3="$http3" '
        'htref="$http_referer" '
        'htua="$http_user_agent" '
        'htxff="$http_x_forwarded_for" '
        'htcip="$http_cf_connecting_ip" '
    ;
