    log_format ips-30
        '$time_iso8601 '
        '$msec '
        'ips="$remote_addr_ipscrub" '
        'q="$query_string" '
        'uri="$uri" '
        'url="$scheme://$host$request_uri" '
        'sts="$status" '
    ;
