    log_format ips-50
        '$time_iso8601 '
        '$msec '
        'ips="$remote_addr_ipscrub" '
        'rqmth="$request_method" '
        'rq="$request" '
        'rquri="$request_uri" '
        'q="$query_string" '
        'uri="$uri" '
        'url="$scheme://$host$request_uri" '
        'sts="$status" '
        'htref="$http_referer" '
        'htua="$http_user_agent" '
        'htxff="$http_x_forwarded_for" '
        'htcip="$http_cf_connecting_ip" '
    ;
