    ssl_certificate /opt/go-acme/lego/ca/pki.goog/certificates/hostname.example.com.pem;
    ssl_certificate_key /opt/go-acme/lego/ca/pki.goog/certificates/hostname.example.com.pem;
    ssl_trusted_certificate /opt/go-acme/lego/ca/pki.goog/certificates/hostname.example.com.pem;
