    ssl_certificate /opt/lego/lego/ca/pki.goog/certificates/hostname.example.com.crt;
    ssl_certificate_key /opt/lego/lego/ca/pki.goog/certificates/hostname.example.com.key;
    ssl_trusted_certificate /opt/lego/lego/ca/pki.goog/certificates/hostname.example.com.crt;
