    ssl_certificate /opt/go-acme/lego/ca/ssl.com/certificates/hostname.example.com.pem;
    ssl_certificate_key /opt/go-acme/lego/ca/ssl.com/certificates/hostname.example.com.pem;
    ssl_trusted_certificate /opt/go-acme/lego/ca/ssl.com/certificates/hostname.example.com.pem;
