    ssl_certificate /etc/certbot/actalis.it/live/hostname.example.com/fullchain.pem;
    ssl_certificate_key /etc/certbot/actalis.it/live/hostname.example.com/privkey.pem;
    ssl_trusted_certificate /etc/certbot/actalis.it/live/hostname.example.com/fullchain.pem;
